CREATE TABLE cover
(
  id INT(8) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  game_id INT(8) UNSIGNED NOT NULL,
  url TEXT NOT NULL,
  cloudinary_id TEXT DEFAULT NULL,
  width INT(4) UNSIGNED NOT NULL,
  height INT(4) UNSIGNED NOT NULL,
  FOREIGN KEY (game_id) REFERENCES games(id)
);