CREATE TABLE game_developer_relation(
  id INT(8) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  game_id INT(6) UNSIGNED NOT NULL,
  developer_id INT(6) UNSIGNED NOT NULL,
  FOREIGN KEY (game_id) REFERENCES games(id)
);