CREATE TABLE game_expansion_relation
(
  id INT(8) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  game_id INT(8) UNSIGNED NOT NULL,
  expansion_id INT(8) UNSIGNED NOT NULL,
  FOREIGN KEY (game_id) REFERENCES games(id)
);