CREATE TABLE pegi
(
  id INT(8) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  game_id INT(8) UNSIGNED NOT NULL,
  synopsis TEXT DEFAULT NULL,
  rating INT(4) DEFAULT NULL,
  FOREIGN KEY (game_id) REFERENCES games(id)
);