CREATE TABLE pegi
(
  id INT(8) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  game_id INT(8) UNSIGNED NOT NULL,
  url TEXT NOT NULL,
  category INT(8) UNSIGNED NOT NULL,
  FOREIGN KEY (game_id) REFERENCES games(id)
);